# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fleet_pb2 as fleet__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fleet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FleetStub:
    """Fleet is the control plane for a fleet of AI accelerator boards.
    Boards run an agent that Registers, Heartbeats, and ReportsJobs.
    Clients submit inference jobs (evals / sims / rollouts) and query state.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/fleet.Fleet/Register',
                request_serializer=fleet__pb2.BoardInfo.SerializeToString,
                response_deserializer=fleet__pb2.RegisterReply.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/fleet.Fleet/Heartbeat',
                request_serializer=fleet__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=fleet__pb2.HeartbeatReply.FromString,
                _registered_method=True)
        self.ReportJob = channel.unary_unary(
                '/fleet.Fleet/ReportJob',
                request_serializer=fleet__pb2.JobResult.SerializeToString,
                response_deserializer=fleet__pb2.Ack.FromString,
                _registered_method=True)
        self.SubmitJob = channel.unary_unary(
                '/fleet.Fleet/SubmitJob',
                request_serializer=fleet__pb2.JobSpec.SerializeToString,
                response_deserializer=fleet__pb2.JobHandle.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/fleet.Fleet/GetJob',
                request_serializer=fleet__pb2.JobHandle.SerializeToString,
                response_deserializer=fleet__pb2.JobStatus.FromString,
                _registered_method=True)
        self.ListJobs = channel.unary_unary(
                '/fleet.Fleet/ListJobs',
                request_serializer=fleet__pb2.Empty.SerializeToString,
                response_deserializer=fleet__pb2.JobList.FromString,
                _registered_method=True)
        self.ListBoards = channel.unary_unary(
                '/fleet.Fleet/ListBoards',
                request_serializer=fleet__pb2.Empty.SerializeToString,
                response_deserializer=fleet__pb2.BoardList.FromString,
                _registered_method=True)
        self.DrainBoard = channel.unary_unary(
                '/fleet.Fleet/DrainBoard',
                request_serializer=fleet__pb2.BoardId.SerializeToString,
                response_deserializer=fleet__pb2.Ack.FromString,
                _registered_method=True)
        self.FleetStats = channel.unary_unary(
                '/fleet.Fleet/FleetStats',
                request_serializer=fleet__pb2.Empty.SerializeToString,
                response_deserializer=fleet__pb2.Stats.FromString,
                _registered_method=True)


class FleetServicer:
    """Fleet is the control plane for a fleet of AI accelerator boards.
    Boards run an agent that Registers, Heartbeats, and ReportsJobs.
    Clients submit inference jobs (evals / sims / rollouts) and query state.
    """

    def Register(self, request, context):
        """board-side
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitJob(self, request, context):
        """client-side
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBoards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DrainBoard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FleetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FleetServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=fleet__pb2.BoardInfo.FromString,
                    response_serializer=fleet__pb2.RegisterReply.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=fleet__pb2.HeartbeatRequest.FromString,
                    response_serializer=fleet__pb2.HeartbeatReply.SerializeToString,
            ),
            'ReportJob': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportJob,
                    request_deserializer=fleet__pb2.JobResult.FromString,
                    response_serializer=fleet__pb2.Ack.SerializeToString,
            ),
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=fleet__pb2.JobSpec.FromString,
                    response_serializer=fleet__pb2.JobHandle.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=fleet__pb2.JobHandle.FromString,
                    response_serializer=fleet__pb2.JobStatus.SerializeToString,
            ),
            'ListJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJobs,
                    request_deserializer=fleet__pb2.Empty.FromString,
                    response_serializer=fleet__pb2.JobList.SerializeToString,
            ),
            'ListBoards': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBoards,
                    request_deserializer=fleet__pb2.Empty.FromString,
                    response_serializer=fleet__pb2.BoardList.SerializeToString,
            ),
            'DrainBoard': grpc.unary_unary_rpc_method_handler(
                    servicer.DrainBoard,
                    request_deserializer=fleet__pb2.BoardId.FromString,
                    response_serializer=fleet__pb2.Ack.SerializeToString,
            ),
            'FleetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.FleetStats,
                    request_deserializer=fleet__pb2.Empty.FromString,
                    response_serializer=fleet__pb2.Stats.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fleet.Fleet', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fleet.Fleet', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Fleet:
    """Fleet is the control plane for a fleet of AI accelerator boards.
    Boards run an agent that Registers, Heartbeats, and ReportsJobs.
    Clients submit inference jobs (evals / sims / rollouts) and query state.
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.Fleet/Register',
            fleet__pb2.BoardInfo.SerializeToString,
            fleet__pb2.RegisterReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.Fleet/Heartbeat',
            fleet__pb2.HeartbeatRequest.SerializeToString,
            fleet__pb2.HeartbeatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.Fleet/ReportJob',
            fleet__pb2.JobResult.SerializeToString,
            fleet__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.Fleet/SubmitJob',
            fleet__pb2.JobSpec.SerializeToString,
            fleet__pb2.JobHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.Fleet/GetJob',
            fleet__pb2.JobHandle.SerializeToString,
            fleet__pb2.JobStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.Fleet/ListJobs',
            fleet__pb2.Empty.SerializeToString,
            fleet__pb2.JobList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBoards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.Fleet/ListBoards',
            fleet__pb2.Empty.SerializeToString,
            fleet__pb2.BoardList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DrainBoard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.Fleet/DrainBoard',
            fleet__pb2.BoardId.SerializeToString,
            fleet__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FleetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.Fleet/FleetStats',
            fleet__pb2.Empty.SerializeToString,
            fleet__pb2.Stats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
